language: node_js
node_js:
  - "6"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
  - npm install -g jspm@beta
  - jspm install
  - npm install -g typings
  - typings install
script: gulp test