"use strict";
var C = require("./NS/C");
exports.C = C;
var CP = require("./NS/CP");
exports.CP = CP;
var CS = require("./NS/CS");
exports.CS = CS;
var LDP = require("./NS/LDP");
exports.LDP = LDP;
var RDF = require("./NS/RDF");
exports.RDF = RDF;
var XSD = require("./NS/XSD");
exports.XSD = XSD;
var VCARD = require("./NS/VCARD");
exports.VCARD = VCARD;
